[window]
opacity = 0.82
padding = {x=14, y=14}

[font]
size = 12
normal = {family = "IBM Plex Mono"}

#[cursor]
#blink_interval = 666 # demons will be happy

[cursor.style]
blinking = "On"

[colors.primary]
background = '#000000'
foreground = '#FFFFFF'
